"""initial_schema

Revision ID: 768887a690fa
Revises: 
Create Date: 2026-03-20 19:56:03.392319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '768887a690fa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_postings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('raw_html', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('posted_date', sa.Date(), nullable=True),
    sa.Column('harvested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('extraction_failed', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_postings_company'), 'job_postings', ['company'], unique=False)
    op.create_index(op.f('ix_job_postings_processed'), 'job_postings', ['processed'], unique=False)
    op.create_index(op.f('ix_job_postings_url'), 'job_postings', ['url'], unique=True)
    op.create_table('skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('skill_type', sa.String(length=50), nullable=True),
    sa.Column('domain', sa.String(length=100), nullable=True),
    sa.Column('subdomain', sa.String(length=100), nullable=True),
    sa.Column('low_confidence', sa.Boolean(), nullable=False),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.Column('embedding_status', sa.String(length=20), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_canonical_name'), 'skills', ['canonical_name'], unique=True)
    op.create_index(op.f('ix_skills_domain'), 'skills', ['domain'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('job_posting_skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_posting_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('context_snippet', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_posting_skills_job_posting_id'), 'job_posting_skills', ['job_posting_id'], unique=False)
    op.create_index(op.f('ix_job_posting_skills_skill_id'), 'job_posting_skills', ['skill_id'], unique=False)
    op.create_table('survey_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('turn_count', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_sessions_session_token'), 'survey_sessions', ['session_token'], unique=True)
    op.create_index(op.f('ix_survey_sessions_status'), 'survey_sessions', ['status'], unique=False)
    op.create_table('survey_extractions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('self_reported_role', sa.String(length=500), nullable=True),
    sa.Column('self_reported_domain', sa.String(length=100), nullable=True),
    sa.Column('classified_domain', sa.String(length=100), nullable=True),
    sa.Column('ai_anxiety_level', sa.String(length=20), nullable=True),
    sa.Column('current_tools', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('upskilling_goals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('key_themes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_llm_extraction', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['survey_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('survey_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['survey_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_messages_session_id'), 'survey_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_survey_messages_session_id'), table_name='survey_messages')
    op.drop_table('survey_messages')
    op.drop_table('survey_extractions')
    op.drop_index(op.f('ix_survey_sessions_status'), table_name='survey_sessions')
    op.drop_index(op.f('ix_survey_sessions_session_token'), table_name='survey_sessions')
    op.drop_table('survey_sessions')
    op.drop_index(op.f('ix_job_posting_skills_skill_id'), table_name='job_posting_skills')
    op.drop_index(op.f('ix_job_posting_skills_job_posting_id'), table_name='job_posting_skills')
    op.drop_table('job_posting_skills')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_skills_domain'), table_name='skills')
    op.drop_index(op.f('ix_skills_canonical_name'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_job_postings_url'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_processed'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_company'), table_name='job_postings')
    op.drop_table('job_postings')
    # ### end Alembic commands ###
